CREATE TABLE Employee (
	Fname varchar(10) NOT NULL,
	Minit char(1),
	Lname varchar(10),
	SSN varchar(9) NOT NULL,
	Bdate varchar(10),
	Address varchar(30),
	sex char(1),
	salary varchar(10),
	SUPER_SSN varchar(9) NOT NULL,
	DNO INT NOT NULL,
	UNIQUE(DNO),
);


ALTER TABLE EMPLOYEE
ADD CONSTRAINT SSN_PK PRIMARY KEY(SSN);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT SUPER_SSN_SSN FOREIGN KEY (SUPER_SSN) REFERENCES Employee(SSN);


CREATE TABLE Department (
	Dname varchar(10) NOT NULL,
	Dnumber INT NOT NULL,
	Mgr_SSN varchar(9) NOT NULL,
	Mgr_start_date Date,
);

ALTER TABLE Department
ADD CONSTRAINT Dnumber_PK PRIMARY KEY(Dnumber);

ALTER TABLE Department
ADD CONSTRAINT Mgr_SSN_SSN FOREIGN KEY (Mgr_SSN) REFERENCES Employee(SSN);


ALTER TABLE Employee
ADD CONSTRAINT Dnumber_DNO FOREIGN KEY (DNO) REFERENCES Department(Dnumber);


CREATE TABLE DEPT_LOCATIONS (
	Dnumber INT NOT NULL,
	Dlocation varchar(20)NOT NULL,
)

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT Dnumber_Dlocation_PK PRIMARY KEY(Dnumber, Dlocation);

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT Dnumber_Dnumber FOREIGN KEY (Dnumber) REFERENCES Department(Dnumber);

CREATE TABLE PROJECT (
	Pname INT NOT NULL,
	Pnumber varchar(20)NOT NULL PRIMARY KEY,
	Plocation varchar(20)NOT NULL,
	Dnum INT NOT NULL,
)

ALTER TABLE PROJECT
ADD CONSTRAINT Dnum_Dnumber FOREIGN KEY (Dnum) REFERENCES Department(Dnumber);


CREATE TABLE WORKS_ON (
	Essn varchar(9) NOT NULL,
	Pno varchar(20) NOT NULL,
	Hours FLOAT,
)

ALTER TABLE WORKS_ON
ADD CONSTRAINT Essn_Pno_PK PRIMARY KEY(Essn, Pno);

ALTER TABLE WORKS_ON
ADD CONSTRAINT Essn_SSN FOREIGN KEY (Essn) REFERENCES Employee(SSN);

ALTER TABLE WORKS_ON
ADD CONSTRAINT Pno_Pnumber FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);

CREATE TABLE DEPENDENT (
	Essn varchar(9) NOT NULL,
	Dependent_name varchar(20) NOT NULL,
	Sex char(1),
	Bdate Date,
	Relationship varchar(10),
)

ALTER TABLE DEPENDENT
ADD CONSTRAINT Essn_Dependent_name_PK PRIMARY KEY(Essn, Dependent_name);

ALTER TABLE DEPENDENT
ADD CONSTRAINT dep_Essn_SSN FOREIGN KEY (Essn) REFERENCES Employee(SSN);


ALTER TABLE Employee DROP CONSTRAINT SUPER_SSN_SSN;
ALTER TABLE Department DROP CONSTRAINT Mgr_SSN_SSN;
ALTER TABLE EMPLOYEE DROP CONSTRAINT Dnumber_DNO;
ALTER TABLE DEPT_LOCATIONS DROP CONSTRAINT Dnumber_Dnumber;
ALTER TABLE PROJECT DROP CONSTRAINT Dnum_Dnumber;
ALTER TABLE WORKS_ON DROP CONSTRAINT Essn_SSN;
ALTER TABLE WORKS_ON DROP CONSTRAINT Pno_Pnumber;
ALTER TABLE DEPENDENT DROP CONSTRAINT Essn_SSN;
DROP TABLE Employee;
DROP TABLE Department;
DROP TABLE DEPT_LOCATIONS;
DROP TABLE PROJECT;
DROP TABLE WORKS_ON;
DROP TABLE DEPENDENT;
